package main

import (
    "context"
    "fmt"
    "os"
    
    "go.temporal.io/sdk/client"
    "go.uber.org/zap"
    
    "polymarket-arbitrage/internal/application/workflow"
    "polymarket-arbitrage/internal/domain/service"
    "polymarket-arbitrage/internal/infrastructure/temporal"
    "polymarket-arbitrage/pkg/config"
    "polymarket-arbitrage/pkg/logger"
)

// App is the root dependency-injected application container.
type App struct {
    Config    *config.Config
    Logger    *logger.Logger
    Temporal  *temporal.Client
    Worker    *temporal.Worker
    Screener  *service.OpportunityScreener
}

func NewApp(
    cfg *config.Config,
    log *logger.Logger,
    temporalClient *temporal.Client,
    worker *temporal.Worker,
    screener *service.OpportunityScreener,
) *App {
    return &App{
        Config:   cfg,
        Logger:   log,
        Temporal: temporalClient,
        Worker:   worker,
        Screener: screener,
    }
}

func (a *App) Start(ctx context.Context) error {
    a.Logger.Info("starting polymarket-arbitrage engine",
        zap.String("env", a.Config.Environment),
        zap.String("temporal_namespace", a.Config.TemporalNamespace),
    )
    
    // Start Temporal worker
    go a.Worker.Start(ctx)
    
    // Start price feed consumers (Polymarket + Binance)
    // Start HTTP/gRPC servers
    
    <-ctx.Done()
    return a.Shutdown(ctx)
}

func (a *App) Shutdown(ctx context.Context) error {
    a.Logger.Info("shutting down")
    a.Worker.Stop()
    a.Temporal.Close()
    return nil
}

func main() {
    app, err := BuildApp() // generated by Wire
    if err != nil {
        fmt.Fprintf(os.Stderr, "failed to build app: %v\n", err)
        os.Exit(1)
    }
    ctx := context.Background()
    if err := app.Start(ctx); err != nil {
        app.Logger.Fatal("startup failed", zap.Error(err))
    }
}
